# Site settings
title: Model Metrics
#email: your-email@domain.com
baseurl: "/model-metrics" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
